import {
  Award,
  Backpack,
  Bell,
  Bike,
  Binoculars,
  BookOpen,
  Bookmark,
  Briefcase,
  Calendar,
  Camera,
  Car,
  Clock,
  Cloud,
  Coffee,
  Compass,
  Crown,
  Download,
  Dumbbell,
  ExternalLink,
  Facebook,
  Feather,
  FileText,
  Film,
  Fish,
  Flag,
  Flame,
  Flower2,
  Footprints,
  Gem,
  Gift,
  Github,
  Globe,
  GraduationCap,
  Handshake,
  Headphones,
  Heart,
  Hotel,
  House,
  Image as ImageGlyph,
  Instagram,
  Key,
  Landmark,
  Leaf,
  Lightbulb,
  Link as LinkIcon,
  Linkedin,
  Luggage,
  Mail,
  Map as MapGlyph,
  MapPin,
  Megaphone,
  MessageCircle,
  Mic,
  Moon,
  Mountain,
  Music,
  Newspaper,
  NotebookPen,
  Package,
  Palette,
  Percent,
  PenTool,
  Phone,
  Pin,
  Plane,
  Play,
  Podcast,
  Radio,
  Rocket,
  Route,
  Send,
  Shield,
  Shirt,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Signpost,
  Snowflake,
  Sparkles,
  Star,
  Store,
  Sun,
  Sunrise,
  Tag,
  Tent,
  Ticket,
  TreePalm,
  Trees,
  Trophy,
  Tv,
  Users,
  Utensils,
  Video,
  Wallet,
  Waves,
  Youtube,
  Zap,
} from 'lucide-react';
import { TikTokGlyph, XGlyph } from '../link-in-bio/BrandGlyphs';
import { CONTENT_ICON_KEYS, iconLabel } from '../../lib/iconCatalog.js';

/** Line icons available for the full-width content buttons, keyed like `iconCatalog.js`. */
export const CONTENT_ICONS = {
  /* travel */
  compass: Compass,
  map: MapGlyph,
  'map-pin': MapPin,
  globe: Globe,
  plane: Plane,
  tent: Tent,
  mountain: Mountain,
  backpack: Backpack,
  route: Route,
  luggage: Luggage,
  binoculars: Binoculars,
  signpost: Signpost,
  ship: Ship,
  car: Car,
  bike: Bike,
  footprints: Footprints,
  hotel: Hotel,
  landmark: Landmark,
  /* nature */
  sun: Sun,
  sunrise: Sunrise,
  waves: Waves,
  palm: TreePalm,
  snowflake: Snowflake,
  leaf: Leaf,
  trees: Trees,
  flower: Flower2,
  cloud: Cloud,
  moon: Moon,
  flame: Flame,
  fish: Fish,
  /* content */
  camera: Camera,
  video: Video,
  film: Film,
  image: ImageGlyph,
  music: Music,
  mic: Mic,
  headphones: Headphones,
  podcast: Podcast,
  pen: PenTool,
  palette: Palette,
  book: BookOpen,
  journal: NotebookPen,
  newspaper: Newspaper,
  feather: Feather,
  file: FileText,
  tv: Tv,
  radio: Radio,
  play: Play,
  /* shop */
  bag: ShoppingBag,
  cart: ShoppingCart,
  tag: Tag,
  gift: Gift,
  percent: Percent,
  store: Store,
  package: Package,
  wallet: Wallet,
  ticket: Ticket,
  shirt: Shirt,
  /* contact */
  mail: Mail,
  message: MessageCircle,
  phone: Phone,
  send: Send,
  calendar: Calendar,
  clock: Clock,
  bell: Bell,
  users: Users,
  handshake: Handshake,
  megaphone: Megaphone,
  /* general */
  link: LinkIcon,
  external: ExternalLink,
  download: Download,
  sparkles: Sparkles,
  zap: Zap,
  heart: Heart,
  star: Star,
  award: Award,
  trophy: Trophy,
  rocket: Rocket,
  lightbulb: Lightbulb,
  bookmark: Bookmark,
  home: House,
  briefcase: Briefcase,
  graduation: GraduationCap,
  coffee: Coffee,
  utensils: Utensils,
  dumbbell: Dumbbell,
  shield: Shield,
  crown: Crown,
  gem: Gem,
  key: Key,
  flag: Flag,
  pin: Pin,
};

/** Russian names for the content icons, used by the picker's accessible names. */
export const CONTENT_ICON_LABELS = Object.fromEntries(
  CONTENT_ICON_KEYS.map((key) => [key, iconLabel(key)])
);

/** Marks that can lead a social icon. */
export const SOCIAL_GLYPHS = {
  telegram: Send,
  youtube: Youtube,
  instagram: Instagram,
  x: XGlyph,
  tiktok: TikTokGlyph,
  facebook: Facebook,
  linkedin: Linkedin,
  whatsapp: MessageCircle,
  github: Github,
  email: Mail,
  phone: Phone,
  link: LinkIcon,
};

/** Marks that are filled shapes rather than outline strokes. */
const FILLED_GLYPHS = new Set(['x', 'tiktok']);

export function resolveContentIcon(key) {
  return CONTENT_ICONS[key] ?? LinkIcon;
}

export function resolveSocialGlyph(key) {
  return SOCIAL_GLYPHS[key] ?? LinkIcon;
}

export function isFilledGlyph(key) {
  return FILLED_GLYPHS.has(key);
}
